# Generated by Django 3.2 on 2022-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
